// This file is autogenerated. Changes will be overwritten.
#include "XKFTU44BVS/moc_communicationclient.cpp"
#include "XKFTU44BVS/moc_responsedispatcher.cpp"
#include "XKFTU44BVS/moc_streamparser.cpp"
#include "AKRC6WZMME/moc_doctorinfowidget.cpp"
#include "KUE7F3CO2C/moc_hello.cpp"
#include "MJCUNQZLOZ/moc_loginwidget.cpp"
#include "ZEUGGMGZAI/moc_patientinfowidget.cpp"
